version: '3.3'
services:
  drone-crud:
    build:
      context: ./drone-crud
      dockerfile: Dockerfile
    ports:
      - 8095:8095
  # user_profile:
  #   build:
  #     context: ./webApp/user-profile/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4200:4200
  #   depends_on:
  #     - db
  #     - user_image_fastapi
# Names our volume
volumes:
  my-db:
