{
 "title": "Teste Infinispan",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instancia", "label": "Instancia", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load JVM (\"$instancia\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "base_cpu_processCpuLoad_percent{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads JVM (\"$instancia\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_thread_daemon_count{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM NonHeapMemory Commited ($instancia)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_committedNonHeap_bytes{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM HeapMemory Commited (\"$instancia\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM HeapMemory Used ($instancia)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM NonHeapMemory Used ($instancia)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_usedNonHeap_bytes{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cache Container ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cache Container Memory Used($instancia)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_health_total_memory_kb{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BufferPool Used Memory($instancia)",
   "type": "stat",
   "description": "The memory used by the NIO pool: direct",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_BufferPool_used_memory_direct_bytes{instance=~\"$instancia\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used - Cliente($instancia)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_data_memory_used{instance=~\"$instancia\"}",
     "legendFormat": "data-{{instance}}"
    },
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_off_heap_memory_used{instance=~\"$instancia\"}",
     "legendFormat": "off-heap-{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Container Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_read_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache container Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_write_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Container Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_remove_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_read_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_write_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente Average Store Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_store_times_mean_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_read_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_write_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_remove_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente - Itens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_cluster_cache_stats_number_of_entries",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario - Itens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_cluster_cache_stats_number_of_entries",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_remove_time_nanos",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente - Persisted Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_cache_store_number_of_persisted_entries",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario - Persisted Itens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_cache_store_number_of_persisted_entries",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente - evictions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_cluster_cache_stats_evictions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario - evictions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_cluster_cache_stats_evictions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cliente - Passivations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_passivation_passivations",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Salario - Passivations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_passivation_passivations",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Camel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Camel Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_status",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Route Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_running_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_failed_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges FailureHandled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_failuresHandled_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_uptime_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inflight Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_context_exchanges_inflight_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_completed_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges Rate/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_total[1m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - Rotas - exchange p/segundo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_total[1m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges ReDelivered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_externalRedeliveries_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - MAX exchange p/segundo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_total[1m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - Rotas - excanges infligit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}