global:
  scrape_interval:     15s
  evaluation_interval: 15s

# rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']  
        labels:
          instance: "prometheus"

  - job_name: grafana
    static_configs:
      - targets: ['localhost:3000']  
        labels:
          instance: "grafana"
  
  - job_name: kml2infinispan
    metrics_path: /q/metrics
    static_configs:
      - targets: ['0.0.0.0:8092']
        labels:
          instance: "kmlPG2infinispan"
      - targets: ['0.0.0.0:8093']
        labels:
          instance: "kmlKafka2infinispan-1"
      - targets: ['0.0.0.0:8094']
        labels:
          instance: "kmlKafka2infinispan-2"
    
  - job_name: dg-cache-monitor
    metrics_path: /q/metrics
    static_configs:
      - targets: ['0.0.0.0:8087']
        labels:
          instance: "dg-cache-monitor"

  - job_name: kafka-connect
    metrics_path: /metrics
    static_configs:
      # - targets: ['0.0.0.0:2181']
      #   labels:
      #     instance: "Zookeeper"
      - targets: ['0.0.0.0:7072']
        labels:
          instance: "Kafka"
      - targets: ['0.0.0.0:7073']
        labels:
          instance: "KafkaConnect"

  - job_name: infinispan
    basic_auth:
      username: 'admin'
      password: 'password'
    # authorization:
    #   type: digest
    static_configs:
      - targets: ['0.0.0.0:11222' ] 
        labels:
          instance: "infinispan-1"
      - targets: ['0.0.0.0:11223' ] 
        labels:
          instance: "infinispan-2"
      - targets: ['0.0.0.0:11224' ] 
        labels:
          instance: "infinispan-3"
